plugins {
    id 'java'
    id 'org.gradle.test-retry' version '1.5.8'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.testng:testng:7.6.1'
    implementation 'org.seleniumhq.selenium:selenium-java:4.5.0'
    testImplementation 'io.github.bonigarcia:webdrivermanager:5.8.0'
}

test {
    useTestNG() {
        def suiteFile = file("src/test/resources/${project.findProperty('suite') ?: 'regression'}.xml")
        suiteXmlFiles = [suiteFile]
        systemProperties = [
            'browser': project.findProperty('browser') ?: 'chrome'
        ]
        threadCount = (project.findProperty('suite') ?: 'regression') == 'smoke' ? 2 : 4
        parallel = 'methods'
    }

    testLogging {
        events "passed", "skipped", "failed"
        showStandardStreams = true
    }
    
    reports {
        html.required = true
        junitXml.required = true
    }
}